# Generated by Django 3.0.8 on 2020-07-28 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messaggio',
            options={'verbose_name': 'Messaggio', 'verbose_name_plural': 'Messaggi'},
        ),
    ]
